name: buildFormatter

on:
  push:
    branches: master
  pull_request:
    branches: master
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: build hello_world_application
        run: |
          cd hello_world_application
          cmake -B _build
          cmake --build _build --target hello
          ./_build/hello
          cd ..
      - name: build solver_application
        run: |
          cd solver_application
          cmake -B _build
          cmake --build _build --target solver
          cd ..
